### ISSUE TITLE
Where is setup-bubb_spell_menu.exe file?

### ISSUE THREAD

**Issue by AnOpenHeresy** [Bubb13/Bubbs-Spell-Menu-Extended#4]
Where is setup-bubb_spell_menu.exe file?

**Comment by Bubb13** [comment]
In the base folder, (given you are on the correct [branch](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/tree/v4-EEex)).

Use the [latest release](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/releases/latest) + "Source code (zip)" to download.

**Comment by AnOpenHeresy** [comment]
OMG, TY I was using (CODE -> Download ZIP) xD BTW GREAT WORK!
