### ISSUE TITLE
idea: working hotkeys in dweomer menu

### ISSUE THREAD

**Issue by erak666** [Bubb13/Bubbs-Spell-Menu-Extended#6]
an idea: on dweomer spell selection menu - make a hotkey for the regular spell pick it's dweomer version

even less clicking for spammable spells: press hotkey to cast dweomer -> press hotkey to pick spell  -> target

example
on this image, pressing "p" would select improved haste from dweomer menu
<img width="408" alt="image" src="https://user-images.githubusercontent.com/55018209/224483625-141136a7-1849-4d8c-9291-a8ce31f98979.png">

**Comment by Bubb13** [comment]
Implemented in [v4.6](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/releases/tag/v4.6).
