### ISSUE TITLE
Minor functional quirks/doable changes?

### ISSUE THREAD

**Issue by TheArtisanBG** [Bubb13/Bubbs-Spell-Menu-Extended#7]
Honestly the spell menu is becoming indispensable. This isn't really an issue since everything I'm about to talk about is so minor, but are any of the below things feasible?

- The only actual glitch I've noticed is that when the menu is up it will close if I click on anything outside of it which is expected but if I switch control to another party member using the number keys the menu will stay up despite no longer reading the input of the chosen spell since I'm not controlling the spellbook's owner anymore. It actually doesn't seem to read any keyboard inputs at all and the menu will stay up even if I open the map or other menus where it stays open in the background and I have to click to close it first. Sometimes it'll stay up even if I reload to a different character.
- I'm attaching a screenshot of my preferred layout of the menu below. I seriously love how this resembles the quick spell menu of NWN2, but I was wondering if making the spellbook change according to the character selected and allowing gameplay inputs while the menu is persistently up like in NWN2 is beyond the abilities of EEEx. I honestly could live with it as it is but if there was any chance this was possible it would make me unbelievably excited.
- 
![Baldr053](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/assets/13630333/f982ebeb-7255-404e-b223-9165b135a2b1)

Thanks for all your efforts in designing the mod.

**Comment by Bubb13** [comment]
Hello! Thanks for the kind words. [v5.0](https://github.com/Bubb13/Bubbs-Spell-Menu-Extended/releases/tag/v5.0)'s Overlay Mode should be what you are looking for. 🙂
